# Generated by Django 4.0.4 on 2022-04-13 01:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=50, verbose_name='Name')),
                ('description', models.CharField(blank=True, default='', max_length=200, verbose_name='Description')),
                ('url', models.URLField(blank=True, default='', verbose_name='URL')),
                ('rating', models.IntegerField(default='1', validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)], verbose_name='Rating')),
            ],
        ),
    ]
