# Generated by Django 4.0.4 on 2022-04-13 02:38

from django.db import migrations, models
import githubprojects.models


class Migration(migrations.Migration):

    dependencies = [
        ('githubprojects', '0002_alter_project_options_alter_project_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='url',
            field=models.URLField(validators=[githubprojects.models.GithubURLValidator()], verbose_name='URL'),
        ),
    ]
