# Generated by Django 4.0.4 on 2022-04-13 02:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('githubprojects', '0003_alter_project_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='rating',
            field=models.DecimalField(decimal_places=2, default='1', max_digits=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Rating'),
        ),
    ]
