# Generated by Django 4.0.4 on 2022-04-15 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('githubprojects', '0006_alter_project_options_webhook'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Webhook',
        ),
    ]
